### ISSUE TITLE
Number formatting options for the x-axis on column charts

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#1]
For instance, if the x-axis labels are years, it would would be great to be able to format them as "01, 02, 03" automatically, as one can already do for the y-axis.

**Comment by elanals** [comment]
So far our column charts weren't rendered with a real 'axis' so to speak, but rather each individual column had it's own label. This made sense for categorical datasets, less so when it comes to visualizing development over time. The good news is that we actually had exactly the improvement you're after here in the pipeline, whereby datasets with a time axis would be rendered with a continuous x axis, as opposed to individually labelled columns. This was already in the later stages of development and were able to push this through on the basis of your request, so you should find that the behaviour there is now akin to that of line charts.

**Comment by palewire** [comment]
That's great. We'll keep an eye out for this improvement.

**Comment by palewire** [comment]
I see it now. Well done.
