### ISSUE TITLE
Correct "–" hyphen length for negative value labels

### ISSUE THREAD

**Issue by LElebee** [datadesk/datawrapper-migration#19]
The symbol for negative value labels should look like this: "–"  Using the option + "-" keys
Currently that symbol displays like this: "-"

See attached PDF for explanation details.
[negative symbols in charts.pdf](https://github.com/datadesk/datawrapper-migration/files/3752466/negative.symbols.in.charts.pdf)

**Comment by LElebee** [comment]
Thank you Elana. I clearly see that in the LAT print design. Not seeing it in the LAT web design.

Lorena

L.I.Elebee
Data Visualization Journalist
Los Angeles Times
Lorena.iniguez@latimes.com
(213) 237-0722

**Comment by LElebee** [comment]
Elena, here is a screenshot of a test chart shown in both print and web style. Shows the web design side with the default “minus” symbol.

[cid:07617C6C-B6AF-4413-A50E-088F3CC63971]


Thanks,

Lorena




From: Art Department <lorena.iniguez@latimes.com<mailto:lorena.iniguez@latimes.com>>
Date: Thursday, October 31, 2019 at 7:30 PM
To: datadesk/datawrapper-migration <reply@reply.github.com<mailto:reply@reply.github.com>>, datadesk/datawrapper-migration <datawrapper-migration@noreply.github.com<mailto:datawrapper-migration@noreply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: Re: [datadesk/datawrapper-migration] Correct "­" hyphen length for negative value labels (#19)

Thank you Elana. I clearly see that in the LAT print design. Not seeing it in the LAT web design.

Lorena

L.I.Elebee
Data Visualization Journalist
Los Angeles Times
Lorena.iniguez@latimes.com
(213) 237-0722

**Comment by elanals** [comment]
My mistake, seems I had somehow missed configuring it for the web theme! Should be good now.

**Comment by LElebee** [comment]
Thank you!
