### ISSUE TITLE
Correct line weights on complex and simple line charts

### ISSUE THREAD

**Issue by LElebee** [datadesk/datawrapper-migration#20]
We use two different line weights for line charts, both for web and print. We use a thinner line for a complex multi-point chart and a thicker one for a simple line chart with less values charted.

WEB
Complex: 2.5 pt. weight rule.  Paired with a small dot to highlight a value point
Simple: 5 pt. weight rule. Paired with a slightly larger dot to highlight a value point.

PRINT
Complex: 2 pt. weight rule.  Paired with a small dot to highlight a value point
Simple: 4 pt. weight rule. Paired with a slightly larger dot to highlight a value point.

See attached PDF.
[line weights in line charts.pdf](https://github.com/datadesk/datawrapper-migration/files/3752534/line.weights.in.line.charts.pdf)

**Comment by elanals** [comment]
Hi @LElebee an update on this ticket:
We don't currently have the infrastructure in place to automatically define a line width depending on the number of values, however what I have done is to define the the first two line width presets available in Datawrapper according to the two values you specified. You can cycle through line widths by clicking on them in the editor:
![image](https://user-images.githubusercontent.com/19191012/67567270-e50c0200-f729-11e9-907a-3809876d069f.png)
Datawrapper includes 4 options here plus 0px thickness for when you want a hidden line. I set it so the first one corresponds to the 'complex' line thickness, and the second one corresponds to the 'simple' line thickness. Take a look and let me know your thoughts.

**Comment by LElebee** [comment]
Thank you, that works!

Lorena
