### ISSUE TITLE
Correct text spacing on PRINT export

### ISSUE THREAD

**Issue by LElebee** [datadesk/datawrapper-migration#22]
The space between the bottom edge of the over the headline rule needs correcting. The space should be 7 pt. 

Leading space in the intro needs to be 9.5 pt. 

See attached.
![text spacing PRINT](https://user-images.githubusercontent.com/17730643/67237677-921c0d00-f400-11e9-89dd-84f7191b0739.jpg)

**Comment by elanals** [comment]
This issue should be fixed for the export. You may notice that the distance in the web preview doesn't look quite right (looks smaller than it comes out), this is due to a current workaround that is in place to ensure that the top line is rendered within frame for the PDF export, and is something that we're looking to implement a more sustainable fix for long term. For the time being however with the current settings you should find that you're getting the correct spacing in the exported result.

**Comment by LElebee** [comment]
The print exports still show placement issues with text that break in more than one line across. See this example preview of a 1 col and the 1 col export. 
![text placement - preview](https://user-images.githubusercontent.com/17730643/67605398-2228c200-f733-11e9-9bae-80163eb68473.jpg)
![1 col print -text placement- pdf](https://user-images.githubusercontent.com/17730643/67605399-2228c200-f733-11e9-8f83-066a3a7fb0bf.jpg)

https://app.datawrapper.de/chart/3KAtf/publish#export-pdf

**Comment by LElebee** [comment]
The note at the bottom also shows with a slight overlap of text lines.

**Comment by LElebee** [comment]
Added annotations export large on pdf export for print.
See the following preview example and pdf export example
![print with annotation preview ](https://user-images.githubusercontent.com/17730643/67605681-e4786900-f733-11e9-8dd2-63a20eefb06b.jpg)
![print annotations pdf export](https://user-images.githubusercontent.com/17730643/67605682-e4786900-f733-11e9-8241-7fb15ae47e14.jpg)

.

**Comment by elanals** [comment]
The line breaking issue in export should also be resolved now, please review.

**Comment by LElebee** [comment]
The spacing of text for charts in general without annotation looks good for both web and print. However, the spacing of text in added annotations still needs work for the print design. Currently the annotations export very large. 
[Annotaton-labels-in print design.pdf](https://github.com/datadesk/datawrapper-migration/files/3796593/Annotaton-labels-in.print.design.pdf)

**Comment by palewire** [comment]
Let's make a new ticket for this. I will file.
