### ISSUE TITLE
Web byline should go in the lower right and not have a prefix. 

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#24]

**Comment by LElebee** [comment]
Please move the source line to the left and keep the byline to the right end of the chart or map.

**Comment by elanals** [comment]
The chart byline is now on the left for the web theme. Please review :)

**Comment by LElebee** [comment]
Thank you Elana. I clearly see that in the LAT print design. Not seeing it in the LAT web design.

Lorena

**Comment by LElebee** [comment]
Yes, It is showing up well, thank you Elana. The previous email I sent referred to the “negative” symbol on minus numbers.

Thanks,
Lorena

From: Art Department <lorena.iniguez@latimes.com<mailto:lorena.iniguez@latimes.com>>
Date: Thursday, October 31, 2019 at 7:26 PM
To: datadesk/datawrapper-migration <reply@reply.github.com<mailto:reply@reply.github.com>>, datadesk/datawrapper-migration <datawrapper-migration@noreply.github.com<mailto:datawrapper-migration@noreply.github.com>>
Cc: Comment <comment@noreply.github.com<mailto:comment@noreply.github.com>>
Subject: Re: [datadesk/datawrapper-migration] Web byline should go in the lower right and not have a prefix. (#24)

Thank you Elana. I clearly see that in the LAT print design. Not seeing it in the LAT web design.

Lorena
