### ISSUE TITLE
Fix needed: Locator map background style resets

### ISSUE THREAD

**Issue by LElebee** [datadesk/datawrapper-migration#25]
Map background style resets back to default upon toggling between L.A.Times web and print styles. See GIF attached of this example. 
![map style changes on web or print style toggle](https://user-images.githubusercontent.com/17730643/67525796-466b9c80-f668-11e9-9006-f1c94cc95a4b.gif)

**Comment by elanals** [comment]
I've created an internal ticket on this problematic behaviour and will keep you posted.

**Comment by elanals** [comment]
This has been fixed, please review.

**Comment by LElebee** [comment]
Thank you Elana for the updates, we are getting close.

Lorena


L.I.Elebee
Data Visualization Journalist
Los Angeles Times
Lorena.iniguez@latimes.com
(213) 237-0722
