### ISSUE TITLE
Fix display of the "a" character

### ISSUE THREAD

**Issue by LElebee** [datadesk/datawrapper-migration#26]
The lower case "a" displays with the upper part of the loop too thin, it looks like a mistake.
Please correct. See the difference in this attachment. Datawrapper display is on the right, our font faces are on the left. This seems to be happening in raster exports. 
![A character](https://user-images.githubusercontent.com/17730643/67527473-f098f380-f66b-11e9-8659-b8278014a8fd.jpg)

**Comment by elanals** [comment]
Hi @LElebee what you're noticing here is just an issue with the low resolution of the export, if you push up the **scale factor** slider before export to 4(or manually input a higher number, I did 5 to test) you should find the result is matches the web preview.

![image](https://user-images.githubusercontent.com/19191012/67573327-5baffc00-f738-11e9-8acf-c229db35d110.png)

From the exported raster:
![image](https://user-images.githubusercontent.com/19191012/67573307-4e930d00-f738-11e9-8029-47056f061523.png)

**Comment by palewire** [comment]
@elanals, can we make that higher scale factor the default setting?

**Comment by LElebee** [comment]
Good to know. Thank you.
Thank you Elana for  your help and response to our questions and requests that we’ve sent out to you. We appreciate it.

Lorena
