### ISSUE TITLE
Correct spacing and size of text on print style export

### ISSUE THREAD

**Issue by LElebee** [datadesk/datawrapper-migration#27]
The spacing between text is too tight. This is visible on pdf export for print stye. The issue is occurring on both charts and maps. Attaching a couple of examples of this issue. 
![headline placement](https://user-images.githubusercontent.com/17730643/67528040-491cc080-f66d-11e9-900f-7c6f556c395f.jpg)
![text size and spacing](https://user-images.githubusercontent.com/17730643/67528041-491cc080-f66d-11e9-88fd-fc6a6d1ac7c7.jpg)

**Comment by LElebee** [comment]
The kearning or tracking of the byline also needs correcting. See attached for specs.
![byline kearning](https://user-images.githubusercontent.com/17730643/67528553-98172580-f66e-11e9-85d8-7cbeadc41cd9.jpg)

**Comment by elanals** [comment]
Both of these issues should be fixed, please review.
