### ISSUE TITLE
Fix bug in the vertical axis for charts

### ISSUE THREAD

**Issue by LElebee** [datadesk/datawrapper-migration#28]
The customization tool was not working properly. After setting the range on the vertical scale to 60,000, the chart scale was broken into increments of 5 which made it look too dense. Tried to customize it,but it wasn't changing. Previously in this example, the vertical scale was incremented by 10 when the display range was maximized at 50,000, but setting back to 50,000 didn't work either.  By increasing the range to 70, it finally stopped displaying it in increments of 5. See attached example.
![US-waste-paper-exports-2](https://user-images.githubusercontent.com/17730643/67529200-4a9bb800-f670-11e9-9164-bfb843e256f5.png)

**Comment by palewire** [comment]
Would it be possible to add an input where you can provide the maximum number of ticks you'd like? I thought d3 supported that.

**Comment by palewire** [comment]
After some discussion on this side, I think we are okay with where things are.
