### ISSUE TITLE
Default scale factor on raster downloads should be 4 or 5

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#29]
To avoid the bug documented in #26

**Comment by elanals** [comment]
Sorry for the wait on this one. Datawrapper offered a feature whereby we can define specific export presets for PNG/PDF, although there wasn't away to apply one of these by default, we now added this, and I created a PNG preset for you with scale factor 5, which is the default so gets applied automatically. Let me know if you'd like any other presets, or any of the other settings specified in this preset (e.g width/height etc)

![image](https://user-images.githubusercontent.com/19191012/68851350-11d28a00-06d6-11ea-974b-7fd6f0a9486c.png)

**Comment by palewire** [comment]
Thank you, @elanals. This is a great solution.
