### ISSUE TITLE
Default color mode for PDF exports should be CMYK

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#30]
We're exporting to PDF to go to print. It would be preferred for the default color there to be CMYK so our producers wouldn't have to remember to click that option every time.

![Screenshot from 2019-10-26 08-49-47](https://user-images.githubusercontent.com/9993/67622278-a92a7880-f7cd-11e9-869f-57f38576ad0d.png)

**Comment by elanals** [comment]
Changed the default settings for export to match the 2 Col preset, please review!
