### ISSUE TITLE
Black bottom line between source line and byline missing on PDF exports to print theme

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#31]
The preview on the site at https://app.datawrapper.de/chart/yHOTp/publish

![Screenshot from 2019-10-26 08-56-14](https://user-images.githubusercontent.com/9993/67622394-91072900-f7ce-11e9-897e-653138c75c0f.png)

The PDF that comes out:

![Screenshot from 2019-10-26 08-58-03](https://user-images.githubusercontent.com/9993/67622407-bf850400-f7ce-11e9-9e8c-3fcc608bcf5e.png)

[yHOTp-cmyk.pdf](https://github.com/datadesk/datawrapper-migration/files/3775006/yHOTp-cmyk.pdf)

**Comment by elanals** [comment]
This should be resolved now, please review
