### ISSUE TITLE
Color palette presets for charts

### ISSUE THREAD

**Issue by LElebee** [datadesk/datawrapper-migration#36]
Requesting to set presets for our standard color palette. 

#1281AA highlight (dark teal)
#83C6E0 standard or secondary (light teal)
#BCBEC0 other color (med gray)
#6D6E71 other color (dark dray)
#B75A36 deficit color (dark orange)
#000000 other color (black)
#EBEBEC background color (light gray)

Extended color palette to be added later.
![LAT standard chart color palette](https://user-images.githubusercontent.com/17730643/68265310-859ed380-0000-11ea-824c-bd04519ff84d.jpg)

**Comment by palewire** [comment]
Ideally those colors would go here. 
![Screenshot from 2019-11-08 07-41-04](https://user-images.githubusercontent.com/9993/68489042-2b1d9700-01fb-11ea-9f3e-cbc06671c1f9.png)

**Comment by elanals** [comment]
I added the colors to the palette, there are two blues in there now that are very similar (your first one #82C6DF and #83C6E0 (listed above as "Standard") should those to be one and the same, and if so, which hex?

![image](https://user-images.githubusercontent.com/19191012/69354678-c7767d80-0c80-11ea-8b1b-25b455ef4648.png)

**Comment by elanals** [comment]
Also, what is "background" referring to - are your charts meant to a filled grey background on the entire iframe?

**Comment by LElebee** [comment]
No. The background gray is a standard color to use for highlighting a period within the data trend. Like this example.  
![gray backround in charts](https://user-images.githubusercontent.com/17730643/70463218-58b36580-1a71-11ea-9496-bec34a4e6d4a.jpg)
