### ISSUE TITLE
Hide the "Design" tab

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#37]
Our use case calls for only two designs, one for web and one for print. They are directly analogous to your existing "mode" options. The result is that there is no reason for our users to ever change the default selection in the "Design" tab.

Instead, if I understand the situation correctly, we will want them to select the style for their chart with the mode button. The existence of the second unnecessary design step can only produce confusion and errors, as seen in #34.

My proposal: Hide the Design the tab. Can it be done?

**Comment by elanals** [comment]
Design tab should now be hidden!

**Comment by palewire** [comment]
I can confirm it. Thank you.
