### ISSUE TITLE
Default blue color for bars, lines and other basic marks should be #82c6df

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#4]
Should be #82c6df

**Comment by elanals** [comment]
Done!

**Comment by elanals** [comment]
If you'd like additional colors in the palette, could you please send those over (hex values for web and the corresponding cmyk values for print) as far as I can see we don't have any information from your end on this so far.

**Comment by palewire** [comment]
We have a "categorical" color scheme for stacked area charts and such that goes up to six colors. It includes:

```        '#3580b1',
        '#ec8431',
        '#ab7fb4',
        '#c89d29',
        '#adc839',
        '#829eb1',```

the light blue default here and its slightly darker blue highlight are intended for two color charts, like lines and bars. We will also sometimes us #ec8431 as a stronger highlight alternative, often in the case of negative values. 

For color ramps on things like choropleths, we have an "ice" and "fire" scale we tend to use for simple things. The colors are:
```
        '#fbf2c7',
        '#f9e39c',
        '#f8d36e',
        '#f4bb6a',
        '#e68a4f',
        '#d15a40',
        '#ab4232',
```
```
        '#edefee',
        '#dadfe2',
        '#c4ccd2',
        '#a6b7c6',
        '#849eae',
        '#607785',
        '#47525d',
```
And then we have a diverging combination of the two
```
        '#e68a4f',
        '#f4bb6a',
        '#f9e39c',
        '#dadfe2',
        '#a6b7c6',
        '#849eae',
```

I don't know how these square with your configuation. If you have more explicit specs for your color style schema, we'd be happy to fill it in given the JSON or whatever.
