### ISSUE TITLE
byline should be float right at at the far edge for all charts. it is not for line charts

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#40]
[See here](https://app.datawrapper.de/chart/1sR8J/visualize#refine-the-chart)

![Screenshot from 2019-11-13 19-29-51](https://user-images.githubusercontent.com/9993/68824534-10f51600-064c-11ea-99af-56278f787e6e.png)

**Comment by elanals** [comment]
This should be fixed now! Sorry for keeping you waiting on this.

**Comment by palewire** [comment]
Thank you.
