### ISSUE TITLE
Map marker text leading

### ISSUE THREAD

**Issue by LElebee** [datadesk/datawrapper-migration#42]
Markers with key under the map Annotation tab.
- Fix the leading on the text for better legibility. The leading currently appears too tight.
https://app.datawrapper.de/edit/1FS9w/markers
![Map text marker leading](https://user-images.githubusercontent.com/17730643/68892951-f7e67680-06d8-11ea-9ad2-82e0e734d16e.jpg)

**Comment by elanals** [comment]
Should be better now for both web & print themes, let me know if it needs more adjusting.

**Comment by palewire** [comment]
Yep. Looks better. Thank you.
