### ISSUE TITLE
Make the 400px wide preview the default

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#45]
The majority of our readers are now on mobile phones. Every chart we make needs to work at small sizes to suit that audience.

We love the mobile preview option in datawrapper's editing panel, but a chartmaker in a hurry may forget to hit the button and proof their chart at the small size. Can we make the middle 400px option the default instead of the 600px desktop view?

This could be done either globally for our account, or surfaced as an option in our settings panel, and we'd be thrilled.

**Comment by elanals** [comment]
The width of a chart on creation should be 375px (irrespective of the selected preview option). I guess the scenario you're referring to is if people resize the chart and then return to it? Or am I missing something

**Comment by palewire** [comment]
I think I submitted this ticket in error. I think my user simply made worse decisions than I anticipated. I will close this ticket open a new one with a request that I think is more on point with the actual use case.
