### ISSUE TITLE
Print PDF export has invisible text

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#51]
You can see it [here on this chart](https://app.datawrapper.de/chart/LBH9h/publish), which I first published as a web chart before doing some more editing and attempting to republish as a print-formatted, two-column PDF.

Here's how the web version initially came out as a PNG export.

![LBH9h-african-americans-in-major-league-baseball](https://user-images.githubusercontent.com/9993/69887479-ffdb1480-129b-11ea-9c9d-6ce7baee3759.png)

Here's how the preview in the final tab looked after I changed to print mode, tweaked the annotation position slightly, and republished it. 

![Screenshot from 2019-11-29 11-30-27](https://user-images.githubusercontent.com/9993/69887496-15503e80-129c-11ea-8680-260277d3935f.png)

But then here's what the resulting PDF looked like when I executed the export. Seems like something is off.

![Screenshot from 2019-11-29 11-30-15](https://user-images.githubusercontent.com/9993/69887508-239e5a80-129c-11ea-81b5-b4d400d63753.png)

You can download the PDF I was given by the export [here](https://github.com/datadesk/datawrapper-migration/files/3906279/LBH9h-cmyk.2.pdf).

**Comment by davidkokkelink** [comment]
Sorry about this - we had an incorrect colour defined. Should be fixed now.

**Comment by palewire** [comment]
This has been fixed.
