### ISSUE TITLE
Fix text outlines on web pdf exports

### ISSUE THREAD

**Issue by LElebee** [datadesk/datawrapper-migration#53]
Text in web charts exported as pdfs are showing up as outlines. The incidents are inconsistent. Sometimes it happens in the headlines, other times elsewhere or in one line of the intro. Incidents happen in more than one chart. See this example: https://app.datawrapper.de/chart/mKXgi/visualize#refine-the-chart

The web font being used for web is Roboto. Is that correct?
Upon opening the pdf portions of text are converted into outlines to after a message pops open to "preserve the appearance." 

Screenshots. of this example:

![pdf preview](https://user-images.githubusercontent.com/17730643/70105564-03510180-15f6-11ea-99c7-3b990f18d6f7.jpg)
![pdf outline view](https://user-images.githubusercontent.com/17730643/70105565-06e48880-15f6-11ea-92cb-6f9c7cf3fb0d.jpg)
![multiple](https://user-images.githubusercontent.com/17730643/70105574-0f3cc380-15f6-11ea-8caa-e9332a037991.jpg)

Is there a simple fix to this?

**Comment by elanals** [comment]
The export font files hadn't been configured for the web theme so far, just configured them so they should now be exporting correctly

**Comment by LElebee** [comment]
Thank you Elana!
