### ISSUE TITLE
Request: Option to make values bold over dark color bars or stacked bars

### ISSUE THREAD

**Issue by LElebee** [datadesk/datawrapper-migration#58]
Requesting to make it an option to Bold values that show within dark background bars or stacked bars. Currently they show as regular font in reversed out labels and are not ideal for print publication. See this illustrated sample to add option for bold reversed out labels over colors.

![Screen Shot 2019-12-09 at 11 52 50 AM](https://user-images.githubusercontent.com/17730643/70469232-87cfd400-1a7d-11ea-81f8-b8d172e61160.jpg)

**Comment by elanals** [comment]
@LElebee It's not really possible to add optional bolding as an option via the UI, but I can offer to set the labels on bars to be permanently bold for your print theme. Would that be an appropriate solution?

**Comment by palewire** [comment]
Yes, I think that short of being able to toggle that always being bold would be the best choice.

**Comment by palewire** [comment]
I believe this has been done and we can close the ticket.
