### ISSUE TITLE
Request: Option to add line breaks in between stacked bar segments

### ISSUE THREAD

**Issue by LElebee** [datadesk/datawrapper-migration#59]
Requesting adding a 1pt. white line breaks between increments of stacked bars for web and print charts. To help contrast on bar breakdowns. See illustrated sample:
![line breaks in bars](https://user-images.githubusercontent.com/17730643/70469958-e5185500-1a7e-11ea-8941-acf6248b41fa.jpg)

**Comment by elanals** [comment]
@LElebee done! please review :)

**Comment by LElebee** [comment]
Hi Elana, thank you! I will take a look.

Lorena
________________________________

**Comment by LElebee** [comment]
Hi Elana. Yes, please. make the values inside the stacked bars as bold labels.

For print, reversed out labels as regular font over color will print very well.

thank you,

Lorena
________________________________
