### ISSUE TITLE
Add election color palette

### ISSUE THREAD

**Issue by LElebee** [datadesk/datawrapper-migration#60]
Add election color swatches. Include general election colors, 5 categories, Dark+light 2-color combos for Democrats and Republicans.

ELECTION COLORS
**Election**
Dems: 5788b8
Reps:d84e55
[LAT-election colors.pdf](https://github.com/datadesk/datawrapper-migration/files/3941833/LAT-election.colors.pdf)

Tied: eddb80
N/A: e2e3e4
Other: d2c9a6

**5 categories**
Orange: e6ad57
Lemon: e6d67c
Violet: b9b1cc
Seagreen: a3dbd0
Gray: 8fa0aa

**Dems + Reps**
Dems dark: 5788b8
Dems light: c8e
Reps dark: d84e55
Reps light: 231f20

**Comment by LElebee** [comment]
Is it possible to separate the election color selection palette from the standard color palette? Or at least distinguish the two color groups?

**Comment by elanals** [comment]
I added the colors. It's unfortunately not currently possible to create groupings within a palette, but this is a a feature we had planned so I'll see what can be done to give it a push on our end. for the election use case it makes a lot of sense!

By the way the 'reps light' "#231f20" appears to be a mistake (it's grey) could you let me know the correct hex value?

**Comment by LElebee** [comment]
Hi Elana, the correct hex value for the lighter Rep color is: f7a1a1
________________________________
