### ISSUE TITLE
Bug: Scale changes in this chart at pdf export for print

### ISSUE THREAD

**Issue by LElebee** [datadesk/datawrapper-migration#62]
On pdf export for print, the scale is over-simplified on pdf and pdf export. Possible to fix this? Keep original scale on pdf export? See sample: https://app.datawrapper.de/chart/TxcWT/visualize#refine-the-chart
see also this recording
![scale changes in pdf export](https://user-images.githubusercontent.com/17730643/70679567-61ab5f00-1c4a-11ea-8b50-ac5a37a04085.gif)

**Comment by LElebee** [comment]
![Screen Shot 2019-12-11 at 5 54 59 PM](https://user-images.githubusercontent.com/17730643/70679664-a20add00-1c4a-11ea-8674-d57e38d2bf22.jpg)
![Screen Shot 2019-12-11 at 5 56 44 PM](https://user-images.githubusercontent.com/17730643/70679665-a20add00-1c4a-11ea-91da-3323a9f3e81c.jpg)

**Comment by palewire** [comment]
I believe this is a case where the original draft chart does not fit our standard two-column preset for print. When I shift to a three-column layout it fits fine.

I suspect that solving this problem requires you setting your preview mode to two columns in the datawrapper administration panel, where you can then configure the chart settings how you'd like.

If I'm wrong about this, please correct me and reopen the ticket.
