### ISSUE TITLE
"Los Angeles Times" credit disappears in print theme when there is no byline

### ISSUE THREAD

**Issue by swethakan** [datadesk/datawrapper-migration#64]
Credits on the bottom should always say: "_Name_ Los Angeles Times" or, if there is no author, just "Los Angeles Times". This is the case on most charts on datawrapper, but in  _certain_ charts the credits do not show up unless there is an author. 
So, If I didn't have an author I wanted to put in, the bottom is left blank.
Here is the issue in action:
![Untitled-1](https://user-images.githubusercontent.com/11639631/71427132-84397100-2669-11ea-8596-3b9875bf47bf.jpg)
![Untitled-2](https://user-images.githubusercontent.com/11639631/71427138-a03d1280-2669-11ea-87bc-cdcefab4417d.jpg)

Is there a way to fix this to always say "Los Angeles Times" or "_Name_ Los Angeles Times"?

**Comment by elanals** [comment]
Fixed

**Comment by palewire** [comment]
This appears to be fixed, as demonstrated by [this example](https://app.datawrapper.de/chart/RJvc8/visualize?mode=print)

![Screenshot from 2020-01-09 09-54-08](https://user-images.githubusercontent.com/9993/72091906-1b3b3580-32c6-11ea-857f-ff78dabc4bc1.png)
