### ISSUE TITLE
Make table body copy smaller for print

### ISSUE THREAD

**Issue by LElebee** [datadesk/datawrapper-migration#67]
See this test table chart sample: https://app.datawrapper.de/table/aM6AD/visualize#annotate

Text, labels in the chart area should be smaller. The labels should be 8 pt. type. No bigger than the intro or headline. 
![Screen Shot 2019-12-19 at 5 50 13 PM](https://user-images.githubusercontent.com/17730643/71697680-a1f38e00-2d6d-11ea-9b71-f22af9ad7b53.jpg)

**Comment by elanals** [comment]
Done, please review

**Comment by palewire** [comment]
Here's what I see now. 

![Screenshot from 2020-01-09 09-51-28](https://user-images.githubusercontent.com/9993/72091698-a10ab100-32c5-11ea-9ad9-c393603e42fb.png)

**Comment by LElebee** [comment]
Thanks Elana. Though on pdf export for print, this is what it looks like.
![Screen Shot 2020-01-09 at 4 12 47 PM](https://user-images.githubusercontent.com/17730643/72115382-b0a4ec80-32fb-11ea-95fe-4220693232cc.jpg)

**Comment by LElebee** [comment]
There are some missing elements. The type size however should be 8 pt. Currently the text outputs as 7pt. The type should also be 100k instead of 80k for print, unless it is reversed.

**Comment by LElebee** [comment]
Sample of bar chart with the category labels also as 7pt. as well as the values inside the bars.
![Screen Shot 2020-01-09 at 4 32 10 PM](https://user-images.githubusercontent.com/17730643/72116043-d0d5ab00-32fd-11ea-8337-2fb55068d480.jpg)

**Comment by elanals** [comment]
-  Changed font size from 7pt to 8pt
- The missing elements are a bug relating the the export of the flags, I've created a ticket on this
- As far as I can see all type is 100K, here's my illustrator screenshot for examples:

![image](https://user-images.githubusercontent.com/19191012/72172754-490f9f80-33d6-11ea-9c6f-ed610b270240.png)

@LElebee could you explain where/how you're seeing 80K? Are you certain you chose cmyk mode for the export?

**Comment by LElebee** [comment]
Yes, cmyk for print. I just exported the sample chart again and it exports as 80k. The value labels inside the bars @elanals

**Comment by LElebee** [comment]
@elanals Here's a gif showing the Datawrapper chart exported as cmyk and opened as cmyk. Labels show up as 80k. See the file opened at end of the gif.
![80k text export](https://user-images.githubusercontent.com/17730643/72179080-1f845300-3399-11ea-80a9-06384f356405.gif)

**Comment by elanals** [comment]
@LElebee Thanks for the the GIF - I thought you were noticing the issue in tables, it was actually an issue affecting inside bar labels though, should be fixed now!

**Comment by LElebee** [comment]
Yes, 8pt. on value category and value labels on charts abroad, but the vertical and horizontal axis scale labels should remain 7 pt (PRINT export). Details in email.
