### ISSUE TITLE
Make arrow chart's line width thicker

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#73]
Today we published our first arrow chart [here](https://app.datawrapper.de/chart/8dmY3). We would like an option to make the line to be thicker, in the way standard line charts be modified. 

![Screenshot from 2020-01-16 14-26-09](https://user-images.githubusercontent.com/9993/72568146-50b6c480-386c-11ea-8dd0-9b36bf7b2ab8.png)

**Comment by elanals** [comment]
There is an option like this in the pipeline, though I can't at this stage say when we might see that being launched. Would you want us to configure your theme so that the arrows are always a bit thicker for the time being? And if so how thick? Currently they're 2px

**Comment by palewire** [comment]
Thank you. Three or four pixels is probably fine for now.

**Comment by elanals** [comment]
The arrows are now 3px

**Comment by palewire** [comment]
Thank you.
