### ISSUE TITLE
Only show prepended symbols on the top tick of y-axis labels

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#74]
As @elanals proposed in #72:

> Currency and % symbols that come from the number format applied in the visualize step are by default shown on every tick, however this can be configured (in your themes) to only show up for the top tick. Would you prefer that?

I believe this is already the behavior for our print theme. Let's make it default for web too.

**Comment by elanals** [comment]
Was actually not the case for either theme, but I just implemented it for both:
![image](https://user-images.githubusercontent.com/19191012/72635079-3bb95e80-395c-11ea-977c-f419ac20462e.png)

![image](https://user-images.githubusercontent.com/19191012/72635182-7fac6380-395c-11ea-873f-4e85f3d066da.png)

**Comment by palewire** [comment]
Thank you!
