### ISSUE TITLE
PDF export clipping edge of line-chart legends

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#75]
[Here](https://app.datawrapper.de/chart/VdbcT/publish#export-pdf) is a line chart prepared for print export. It looks good.

![Screenshot from 2020-01-18 08-06-13](https://user-images.githubusercontent.com/9993/72666702-ab196780-39c9-11ea-8def-8a01388b7500.png)

But after the PDF is downloaded, the first key item for English has its color swatch clipped by the left edge. 

![Screenshot from 2020-01-18 08-06-45](https://user-images.githubusercontent.com/9993/72666712-c1272800-39c9-11ea-8ccf-8663d443fc1b.png)

This is confirmed by zooming in closer on the PDF.

![Screenshot from 2020-01-18 08-07-03](https://user-images.githubusercontent.com/9993/72666715-c97f6300-39c9-11ea-89cf-65c96c22c04e.png)

**Comment by elanals** [comment]
Ok, investigated this one and looks like there's a bug whereby with the configuration applied to the swatches to make the ends flat. I applied that setting based on your styleguide, but it's not getting correctly carried over to the export. I can get this fixed, but I'd just like to confirm which type of line ends you'd like for the swatches - rounded or flat?

**Comment by palewire** [comment]
Rounded is fine.

**Comment by elanals** [comment]
Ok, should be fine now.

**Comment by palewire** [comment]
Thank you.
