### ISSUE TITLE
Design tab content still showing up without the tab

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#81]
As seen [here](https://app.datawrapper.de/chart/H9Bv4/visualize#proceed)

![Screenshot from 2020-01-26 10-05-49](https://user-images.githubusercontent.com/9993/73139506-82c1e680-4023-11ea-84af-9f285de20ba3.png)

**Comment by elanals** [comment]
Really sorry for neglecting to attend to this for so long. 

The content of the design tab will now no longer display, however the implementation isn't perfect. The reason being that the current approach to removing the design tab is simply css that hides it. This means it's not possible to navigate to the design tab by clicking on it, however it is still possible to navigate to it via the "Proceed" button, which is something that I don't think we could adjust without introducing more complex logic for actually deactivating this tab entirely - I'll have to look into the options here. In the meantime though, I also hid all the content of the design tab, which means when navigating to it via the "Proceed" button, users will see this:

![image](https://user-images.githubusercontent.com/19191012/75231328-875df400-57b5-11ea-8cb5-ee81f6b11f12.png)

Doesn't make much sense from a UI perspective, but at least will prevent unwanted settings getting applied here. Let me know if you think this is a bad idea for whatever reason.

**Comment by palewire** [comment]
thank you.
