### ISSUE TITLE
Overline and underline not appear in PDF print export

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#85]
[Here's the chart](https://datawrapper.dwcdn.net/Unhlp/1/) with the bug.

![Screenshot from 2020-05-05 16-32-48](https://user-images.githubusercontent.com/9993/81125807-1db54100-8eee-11ea-8a29-f8b2004facd2.png)

[Unhlp-cmyk.pdf](https://github.com/datadesk/datawrapper-migration/files/4584153/Unhlp-cmyk.pdf)

**Comment by elanals** [comment]
Fixed!
