### ISSUE TITLE
Footer and credit falling off the PDF export in print mode

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#86]
[Here is](https://app.datawrapper.de/chart/wkZ63/publish#export-pdf) what's in the preview on your site:

![Screenshot from 2020-05-13 15-33-51](https://user-images.githubusercontent.com/9993/81872765-43b29500-952f-11ea-9786-cdd6f6bcea2b.png)

Where's what comes out of the PDF export:

![Screenshot from 2020-05-13 15-34-03](https://user-images.githubusercontent.com/9993/81872778-47deb280-952f-11ea-9aa6-8b593a4f1fac.png)

Note the clipped bottom.

**Comment by elanals** [comment]
Very sorry for this and for the wait on a resolution. It should be better now. Just one thing I wanted to flag though - you'll notice that the spacing between the author credit (byline) and the "Los Angeles Times" looks a little big in the **preview**, although it should look right in the **exported version**. Letter-spacing between neighbouring blocks isn't handled quite right at the moment and without the extra margin the two blocks of text wind up pressed up against each other in the export. This is just temporary until we fix the bug though!

**Comment by palewire** [comment]
This was fixed.
